package client;

import Constants.Constants;
import DataMessaging.DataAddress;
import DataMessaging.Login;
import Exceptions.ClientNotLoggedInException;
import Exceptions.CopyFileException;
import Exceptions.CreateAccountException;
import Exceptions.GetFileContentException;
import Exceptions.MakeDirException;
import Exceptions.RemoveFileOrDirException;
import Exceptions.ServerConnectionException;
import Exceptions.UploadException;
import Exceptions.UsernameOrPasswordIncorrectException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTextField;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreePath;

/**
 * @author Daniel Moreira
 * @author Hugo Santos
 * @author Tiago Santos 
 */

public class ClientGUI extends JFrame implements Constants, Observer {
    
    // <editor-fold defaultstate="collapsed" desc=" Variables ">
    Client client;
    static String username;
    static String ipAddress;
    static String portAddress;
    static String password;
    static String passwordConfirmation;
    static String homePath;
    static String copy;
    static int option;
    static boolean repeatDialogInput = false;
    static boolean cancelLoginCycle = false;
    static boolean cancelCreateAccountCycle = false;
    ArrayList<DataAddress> onlineServer = null;
    ArrayList<DataAddress> onlineClient = null;
    private javax.swing.JTree tree;
    DefaultMutableTreeNode root, home;
    public JPopupMenu popup;
    // </editor-fold>
    
    public ClientGUI() {
        initComponents();
        initTree();
        
        // <editor-fold defaultstate="collapsed" desc=" Mostrar InputDialog para escolher o nome/IPServerDirectory/PortServerDirectory ">
        do {
            JTextField inputUsernameTextField = new JTextField();
            JTextField inputIpAddressDirectoryServiceTextField = new JTextField();
            JTextField inputPortDirectoryServiceTextField = new JTextField();
            
            // <editor-fold defaultstate="collapsed" desc=" PARA TIRAR CONSTANTES NO INICIO ">
            inputUsernameTextField.setText("Hugo");
            inputIpAddressDirectoryServiceTextField.setText("localhost");
            inputPortDirectoryServiceTextField.setText("6000");
            // </editor-fold>
            

            Object[] message = {"Username:", inputUsernameTextField, 
                "SD Address:", inputIpAddressDirectoryServiceTextField, 
                "SD Port:", inputPortDirectoryServiceTextField};
            option = JOptionPane.showConfirmDialog(null, message, "Connect to Directory Service",
                     JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
            if(option == JOptionPane.OK_OPTION) {
                username = inputUsernameTextField.getText();
                ipAddress = inputIpAddressDirectoryServiceTextField.getText();
                portAddress = inputPortDirectoryServiceTextField.getText();
            } else
                System.exit(0);
            
            // <editor-fold defaultstate="collapsed" desc=" Create Client ">
            this.client = new Client(username, ipAddress, portAddress);
            this.client.addObserver(this);
            // </editor-fold>
            
        } while (username.isEmpty() || ipAddress.isEmpty() || portAddress.isEmpty() || option != JOptionPane.OK_OPTION || client.checkClientExists());
        // </editor-fold>
        
        // <editor-fold defaultstate="collapsed" desc=" Enviar/Receber mensagem para atualizar as listas ">
        client.getAllLists();
        // </editor-fold>
        
        this.setTitle(username);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelServers = new javax.swing.JLabel();
        jLabelClients = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaMessages = new javax.swing.JTextArea();
        jButtonBroadcast = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListServers = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jListClients = new javax.swing.JList<>();
        jButtonRefreshLists = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);

        jLabelServers.setText("Servers:");

        jLabelClients.setText("Clients:");

        jTextAreaMessages.setEditable(false);
        jTextAreaMessages.setColumns(20);
        jTextAreaMessages.setRows(5);
        jScrollPane4.setViewportView(jTextAreaMessages);

        jButtonBroadcast.setText("Broadcast Message");
        jButtonBroadcast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBroadcastMouseClicked(evt);
            }
        });

        jListServers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListServers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListServersMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jListServers);

        jListClients.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListClientsMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jListClients);

        jButtonRefreshLists.setText("Refresh Lists");
        jButtonRefreshLists.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRefreshListsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBroadcast)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelServers)
                                    .addComponent(jLabelClients)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jButtonRefreshLists)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonRefreshLists)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelServers)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabelClients)
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBroadcast)
                        .addContainerGap(114, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void initTree(){
        root = new DefaultMutableTreeNode("Root");
        tree = new javax.swing.JTree(root);
        home = new DefaultMutableTreeNode("C:");
        root.add(home);
        homePath = File.listRoots()[0].toString();
        addFiles(new ArrayList<>(Arrays.asList(File.listRoots()[0].listFiles())), home);
        jScrollPane1.setViewportView(tree);
        
        tree.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent me) {
              doMouseClicked(me);
            }
        });
    }
    
    // <editor-fold defaultstate="collapsed" desc=" Events ">
    private void jListServersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListServersMouseClicked
        // TODO add your handling code here:
        popup = new JPopupMenu();
        JMenuItem itemLogin, itemLogout, itemRegister;
        
        if(!this.jListServers.isSelectionEmpty()) {
            if (evt.getButton() == 3) {
                // <editor-fold defaultstate="collapsed" desc=" Login Item (PopUpMenu) ">
                itemLogin = new JMenuItem("Login");
                itemLogin.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        do {
                            repeatDialogInput = false;
                            cancelLoginCycle = false;
                            // <editor-fold defaultstate="collapsed" desc=" Mostrar InputDialog para escolher o username e password ">
                            do {
                                JTextField inputUsernameTextField = new JTextField();
                                JTextField inputPasswordTextField = new JTextField();
                                
                                Object[] message = {"Username:", inputUsernameTextField, "Password:", inputPasswordTextField};
                                option = JOptionPane.showConfirmDialog(null, message, "Login", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
                                if(option == JOptionPane.OK_OPTION) {
                                    username = inputUsernameTextField.getText();
                                    password = inputPasswordTextField.getText();
                                } else if(option == JOptionPane.CANCEL_OPTION) {
                                    cancelLoginCycle = true;
                                    break;
                                }
                            } while (username.isEmpty() || password.isEmpty());
                            // </editor-fold>
                            
                            if (cancelLoginCycle == false) {
                                try {
                                    client.Login(new Login(username, password), onlineServer.get(jListServers.getSelectedIndex()));
                                } catch (ServerConnectionException | UsernameOrPasswordIncorrectException ex) {
                                    repeatDialogInput = true;
                                    JOptionPane.showConfirmDialog(rootPane, ex, "Login error", JOptionPane.OK_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE);
                                } catch (ClientNotLoggedInException | CreateAccountException | MakeDirException | RemoveFileOrDirException | CopyFileException | GetFileContentException ex) {} catch (UploadException ex) {
                                    Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }
                        } while(repeatDialogInput);
                        if(!cancelLoginCycle){
                            DefaultMutableTreeNode server = new DefaultMutableTreeNode("remote" + onlineServer.get(jListServers.getSelectedIndex()).getName());
                            root.add(server);
                            try {
                                addFiles(client.GetWorkingDirContent(onlineServer.get(jListServers.getSelectedIndex())), server);
                            } catch (ServerConnectionException ex) {
                                JOptionPane.showConfirmDialog(rootPane, ex, "Get Dir Content error", JOptionPane.OK_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE);
                            } catch (UsernameOrPasswordIncorrectException | ClientNotLoggedInException | CreateAccountException | MakeDirException | RemoveFileOrDirException | CopyFileException | GetFileContentException ex) {} catch (UploadException ex) {
                                Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    }
                });
                // </editor-fold>
                // <editor-fold defaultstate="collapsed" desc=" New Account Item (PopUpMenu) ">
                itemRegister = new JMenuItem("New account");
                itemRegister.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        // <editor-fold defaultstate="collapsed" desc=" Mostrar InputDialog para escolher o username e password ">
                        do {
                            JTextField inputUsernameTextField = new JTextField();
                            JTextField inputPasswordTextField = new JTextField();
                            JTextField inputPasswordAgainTextField = new JTextField();

                            Object[] message = {"Username:", inputUsernameTextField, 
                                                "Password:", inputPasswordTextField,
                                                "Confirm Password:", inputPasswordAgainTextField};
                            option = JOptionPane.showConfirmDialog(null, message, "Create New Account", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
                            if (option == JOptionPane.OK_OPTION) {
                                username = inputUsernameTextField.getText();
                                password = inputPasswordTextField.getText();
                                passwordConfirmation = inputPasswordAgainTextField.getText();
                                cancelCreateAccountCycle = false;
                            } else if (option == JOptionPane.CANCEL_OPTION) {
                                cancelCreateAccountCycle = true;
                            }
                            if(!password.equals(passwordConfirmation))
                               JOptionPane.showConfirmDialog(rootPane, "Palavra pass não coincide", "Error", JOptionPane.OK_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE);
                        } while (username.isEmpty() || password.isEmpty() || !password.equals(passwordConfirmation));
                        // </editor-fold>
                        
                        if (cancelCreateAccountCycle == false) {
                            try {
                                client.CreateAccount(new Login(username, password), onlineServer.get(jListServers.getSelectedIndex()));
                            } catch (ServerConnectionException | CreateAccountException ex) {
                                JOptionPane.showConfirmDialog(rootPane, ex, "Error", JOptionPane.OK_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE);
                            } catch (UsernameOrPasswordIncorrectException | ClientNotLoggedInException | MakeDirException | RemoveFileOrDirException | CopyFileException | GetFileContentException ex) {/*ignore*/} catch (UploadException ex) {
                                Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    }
                });
                // </editor-fold>
                // <editor-fold defaultstate="collapsed" desc=" Logout Item (PopUpMenu) ">
                itemLogout =  new JMenuItem("Logout");
                itemLogout.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        try {
                            client.Logout(new Login(username, password), onlineServer.get(jListServers.getSelectedIndex()));
                        } catch (ServerConnectionException | ClientNotLoggedInException ex) {
                           JOptionPane.showConfirmDialog(rootPane, ex, "Logout error", JOptionPane.OK_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE);
                        }catch (UsernameOrPasswordIncorrectException | CreateAccountException | MakeDirException | RemoveFileOrDirException | CopyFileException | GetFileContentException ex) {/*ignorar*/} catch (UploadException ex) {
                            Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        root.remove(findNode(root, "remote" + onlineServer.get(jListServers.getSelectedIndex()).getName()));
                        UpdateTree();
                    }
                });
                // </editor-fold>
                
                // <editor-fold defaultstate="collapsed" desc=" Adicionar itens ao PopUpMenu/ Mostrar PopUpMenu ">
                popup.add(itemLogin);
                popup.add(itemRegister);
                popup.add(itemLogout);
                popup.show(this.jListServers, evt.getX(), evt.getY());
                // </editor-fold>
            }
        }
    }//GEN-LAST:event_jListServersMouseClicked

    private void jButtonRefreshListsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRefreshListsMouseClicked
        // TODO add your handling code here:
        // <editor-fold defaultstate="collapsed" desc=" Enviar/Receber mensagem para atualizar as listas ">
        client.getAllLists();
        // </editor-fold>
    }//GEN-LAST:event_jButtonRefreshListsMouseClicked

    private void jListClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListClientsMouseClicked
        // TODO add your handling code here:
        if (!this.jListClients.isSelectionEmpty()){
            if (evt.getClickCount() == 2){
                DataAddress usernameToSend = this.onlineClient.get(this.jListClients.getSelectedIndex());
                String title = "Message to " + usernameToSend.getName();
                JFrame frame = new JFrame(title);
                
                String aux = JOptionPane.showInputDialog(frame, "Input your message", title, JOptionPane.OK_CANCEL_OPTION);
                String message = "[" + username + " - To " + usernameToSend.getName() + "] -> " + aux;
                if (!aux.isEmpty() || aux != null)
                    client.sendMessageTo(usernameToSend, message);
            }
        }
    }//GEN-LAST:event_jListClientsMouseClicked

    private void jButtonBroadcastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBroadcastMouseClicked
        // TODO add your handling code here:
        if (this.onlineClient.isEmpty())
            return;
        
        String title = "Message to All users";
        JFrame frame = new JFrame(title);
        String aux = JOptionPane.showInputDialog(frame, "Input your message", title, JOptionPane.OK_CANCEL_OPTION);
        String message = "[" + username + " - To All] -> " + aux;
        if (!aux.isEmpty() || aux != null)
            client.sendMessageToAll(message);
    }//GEN-LAST:event_jButtonBroadcastMouseClicked

    private void doMouseClicked(MouseEvent me) {
        popup = new JPopupMenu();
        JMenuItem itemCopy, itemPaste, itemCut, itemMakedir, itemRemove;
        final TreePath tp = tree.getPathForLocation(me.getX(), me.getY());

        if (tp != null) {   //Se estiver alguma coisa selecionada
            if (me.getButton() == 1 && me.getClickCount() == 2) {    //É para abrir
                if (tp.getPathCount() == 3) {
                    if (((DefaultMutableTreeNode)tp.getLastPathComponent()).getAllowsChildren()){   // Se é ficheiro
                        String fatherName = tp.getParentPath().getLastPathComponent().toString();
                        if (!fatherName.equals("C:")) {
                            try {
                                DefaultMutableTreeNode fatherNode = findNode(root, fatherName);
                                fatherNode.removeAllChildren();
                                addFiles(client.ChangeDirectory(fatherName.replace("remote",""), tp.getLastPathComponent().toString()), fatherNode);

                            } catch (ServerConnectionException ex) { //apanhar
                                JOptionPane.showConfirmDialog(rootPane, ex, "Change dir error", JOptionPane.OK_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE);
                            } catch (UsernameOrPasswordIncorrectException | ClientNotLoggedInException | CreateAccountException | MakeDirException | RemoveFileOrDirException | CopyFileException | GetFileContentException ex) {} catch (UploadException ex) {
                                Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        } else {
                            DefaultMutableTreeNode fatherNode = findNode(root, fatherName);
                            fatherNode.removeAllChildren();
                            addFiles(HomeChangeDirectory(tp.getLastPathComponent().toString()), fatherNode);
                        }
                    } else
                            try {
                                client.GetFileContent(tp.getParentPath().getLastPathComponent().toString().replace("remote", ""), client.GetWorkingDirPath(tp.getParentPath().getLastPathComponent().toString().replace("remote", "")) + tp.getLastPathComponent().toString());
                    } catch (ServerConnectionException ex) {
                        Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (UsernameOrPasswordIncorrectException ex) {
                        Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClientNotLoggedInException ex) {
                        Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (CreateAccountException ex) {
                        Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (MakeDirException ex) {
                        Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (RemoveFileOrDirException ex) {
                        Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (CopyFileException ex) {
                        Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (GetFileContentException ex) {
                        Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (UploadException ex) {
                        Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } else if (me.getButton() == 3) {
                if (tp.getPathCount() == 2) {
                    //Botao direito e servidor
                    // <editor-fold defaultstate="collapsed" desc=" MakeDir ">
                    itemMakedir = new JMenuItem("MakeDir");
                    itemMakedir.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            //  JFrame frame = new JFrame(title);
                            String title = "MakeDir";
                            JFrame frame = new JFrame(title);
                            String aux = JOptionPane.showInputDialog(null, "Choose folder name", JOptionPane.OK_OPTION);
                            if (!aux.isEmpty() || aux != null) {
                                if (tp.getLastPathComponent().toString().equals("C:")) {
                                    if(HomeMakeDir(aux)){
                                        findNode(root, tp.getLastPathComponent().toString()).add(new DefaultMutableTreeNode(aux));
                                        UpdateTree();
                                    } else
                                        JOptionPane.showConfirmDialog(rootPane, "It's impossible to create that directory.\nTry again later.", "Make dir error", JOptionPane.OK_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE);
                                } else {
                                    try {
                                        client.MakeDir(tp.getLastPathComponent().toString().replace("remote", ""), aux);
                                        findNode(root, tp.getLastPathComponent().toString()).add(new DefaultMutableTreeNode(aux));
                                        UpdateTree();
                                    } catch (ServerConnectionException | MakeDirException ex) {
                                        JOptionPane.showConfirmDialog(rootPane, ex, "Make dir error", JOptionPane.OK_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE);
                                    } catch (UsernameOrPasswordIncorrectException | ClientNotLoggedInException | CreateAccountException | RemoveFileOrDirException | CopyFileException | GetFileContentException ex) {} catch (UploadException ex) {
                                        Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                }
                            }
                        }
                    });
                    popup.add(itemMakedir);
                    // </editor-fold>
                    // <editor-fold defaultstate="collapsed" desc=" Paste Folder/File ">
                    itemPaste = new JMenuItem("Paste");
                    itemPaste.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            if (tp.getLastPathComponent().toString().equals(copy.substring(0, copy.indexOf(File.separator)))){
                                try {
                                    UpdateWorkingDirectory(findNode(root, tp.getParentPath().getLastPathComponent().toString()), client.CopyAndPaste(tp.getLastPathComponent().toString().replace("remote", ""), copy));
                                } catch (ServerConnectionException | CopyFileException ex) {
                                    JOptionPane.showConfirmDialog(rootPane, ex, "Copy and Paste error", JOptionPane.OK_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE);
                                } catch (UsernameOrPasswordIncorrectException | ClientNotLoggedInException | CreateAccountException | MakeDirException | RemoveFileOrDirException | GetFileContentException ex) {} catch (UploadException ex) {
                                    Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            } else{
                                String serverOrigem = copy.substring(0, copy.indexOf(File.separator));
                                String serverDestino = tp.getLastPathComponent().toString();
                                byte[] barray;
                                if(serverOrigem.equals("C:")){
                                    barray = HomeDownload(copy);
                                } else 
                                    try {
                                        //barray = client.Download(serverOrigem.replace("remote", ""), copy);
                                        client.Download(serverOrigem.replace("remote", ""), copy);
                                } catch (ServerConnectionException | GetFileContentException ex) {
                                    JOptionPane.showConfirmDialog(rootPane, ex, "Download error", JOptionPane.OK_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE);
                                } catch (UsernameOrPasswordIncorrectException | ClientNotLoggedInException | CreateAccountException | MakeDirException | RemoveFileOrDirException | CopyFileException ex) {} catch (UploadException ex) {
                                    Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                                }
                                
                                if(serverDestino.equals("C:")){
                                    
                                } else 
                                    try {
                                        UpdateWorkingDirectory(findNode(root, tp.getLastPathComponent().toString()), client.Upload(tp.getLastPathComponent().toString().replace("remote", "")));
                                } catch (ServerConnectionException ex) {
                                    Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                                } catch (UsernameOrPasswordIncorrectException ex) {
                                    Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                                } catch (ClientNotLoggedInException ex) {
                                    Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                                } catch (CreateAccountException ex) {
                                    Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                                } catch (MakeDirException ex) {
                                    Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                                } catch (RemoveFileOrDirException ex) {
                                    Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                                } catch (CopyFileException ex) {
                                    Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                                } catch (GetFileContentException ex) {
                                    Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                                } catch (UploadException ex) {
                                    Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }
                        }
                    });
                    popup.add(itemPaste);
                    // </editor-fold>
                } else if (tp.getPathCount() == 3) {
                    if (!((DefaultMutableTreeNode)tp.getLastPathComponent()).getAllowsChildren()) {
                        //Botao direito nos ficheiros
                        // <editor-fold defaultstate="collapsed" desc=" Copy Folder/File ">
                        itemCopy = new JMenuItem("Copy");
                        itemCopy.addActionListener(new ActionListener() {
                            @Override
                            public void actionPerformed(ActionEvent e) {
                                System.out.println("Enviar Copy para o servidor.");
                                try {
                                    copy = client.GetWorkingDirPath(tp.getParentPath().getLastPathComponent().toString().replace("remote","")) + tp.getLastPathComponent().toString();
                                } catch (ServerConnectionException ex) {
                                    JOptionPane.showConfirmDialog(rootPane, ex, "Make dir error", JOptionPane.OK_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE);
                                } catch (UsernameOrPasswordIncorrectException | ClientNotLoggedInException | CreateAccountException | MakeDirException | RemoveFileOrDirException | CopyFileException | GetFileContentException ex) {} catch (UploadException ex) {
                                    Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }
                        });
                        popup.add(itemCopy);
                        // </editor-fold>
                        // <editor-fold defaultstate="collapsed" desc=" Cut Folder/File ">
                        itemCut = new JMenuItem("Cut");
                        itemCut.addActionListener(new ActionListener() {
                            @Override
                            public void actionPerformed(ActionEvent e) {
                                System.out.println("Enviar Cut para o servidor.");
                                //client.GetFilesInDirectory(me.);
                            }
                        });
                        popup.add(itemCut);
                        // </editor-fold>
                    }
                    //Botão direito na pasta ou ficheiro
                    // <editor-fold defaultstate="collapsed" desc=" Remove Folder/File ">
                    itemRemove = new JMenuItem("Remove");
                    itemRemove.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            if(tp.getParentPath().getLastPathComponent().toString().equals("C:")){
                                if(HomeRemove(tp.getLastPathComponent().toString())){
                                    DefaultMutableTreeNode fatherNode = findNode(root, tp.getParentPath().getLastPathComponent().toString());
                                    DefaultMutableTreeNode childNode = findNode(fatherNode, tp.getLastPathComponent().toString());
                                    fatherNode.remove(childNode);
                                    UpdateTree();
                                } else
                                    JOptionPane.showConfirmDialog(rootPane, "It's impossible to remove the file. If it is a directory, make sure it is empty.", "Remove error", JOptionPane.OK_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE);
                            } else {
                                try{
                                    client.Remove(tp.getParentPath().getLastPathComponent().toString().replace("remote", ""), tp.getLastPathComponent().toString());
                                    DefaultMutableTreeNode fatherNode = findNode(root, tp.getParentPath().getLastPathComponent().toString());
                                    DefaultMutableTreeNode childNode = findNode(fatherNode, tp.getLastPathComponent().toString());
                                    fatherNode.remove(childNode);
                                    UpdateTree();
                                } catch (ServerConnectionException | RemoveFileOrDirException ex) {
                                    JOptionPane.showConfirmDialog(rootPane, ex, "Remove error", JOptionPane.OK_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE);
                                } catch (UsernameOrPasswordIncorrectException | ClientNotLoggedInException | CreateAccountException | MakeDirException | CopyFileException | GetFileContentException ex) {} catch (UploadException ex) {
                                    Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }
                        }
                    });
                    popup.add(itemRemove);
                    // </editor-fold>
                }
                popup.show(this.jScrollPane1, me.getX(), me.getY());
            }
        } else
            System.out.println("No selection");
    }    
    // </editor-fold>
    
    private void UpdateTree(){
        tree.updateUI();
        jScrollPane1.repaint();
    }
    
    private void UpdateWorkingDirectory(DefaultMutableTreeNode fatherNode, ArrayList<File> files){
        fatherNode.removeAllChildren();
        addFiles(files, fatherNode);
        UpdateTree();
    }
    
    private DefaultMutableTreeNode findNode(DefaultMutableTreeNode fatherNode, String name){
        for(int i= 0; i < fatherNode.getChildCount(); i++)
            if(fatherNode.getChildAt(i).toString().equals(name))
                return (DefaultMutableTreeNode) fatherNode.getChildAt(i);
        return null;
    }
    
    private byte[] HomeDownload(String path){
        try {
            return Files.readAllBytes((new File(path)).toPath());
        } catch (IOException ex) {
            return null;
        }
    }
    
    private boolean HomeRemove(String fileName){
        File file = new File(homePath + File.separator + fileName);
        return file.delete();
    }
    
    private boolean HomeMakeDir(String newDirName){
        File file = new File(homePath + File.separator + newDirName);
        return file.mkdir();
    }
    
    private ArrayList<File> HomeChangeDirectory(String file){
        if(file.contains(homePath)){
            homePath = homePath.replace(homePath.substring(homePath.lastIndexOf(File.separator),homePath.length()),"");
            if(homePath.equals("C:"))
                homePath+=File.separator;
        }else{
            if(!(homePath.charAt(homePath.length()-1) == File.separatorChar))
                homePath += File.separator;
            homePath += file;
        }
        File f = new File(homePath);
        if (f.listFiles() != null)
            return new ArrayList<>(Arrays.asList(f.listFiles()));
        return null;
    }
    // <editor-fold defaultstate="collapsed" desc=" Variables declaration - do not modify ">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBroadcast;
    private javax.swing.JButton jButtonRefreshLists;
    private javax.swing.JLabel jLabelClients;
    private javax.swing.JLabel jLabelServers;
    private javax.swing.JList<String> jListClients;
    private javax.swing.JList<String> jListServers;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextAreaMessages;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>
    
    private void addFiles(ArrayList<File> files, DefaultMutableTreeNode remote) {
        if (files != null){
            for (File f: files){
                DefaultMutableTreeNode node = new DefaultMutableTreeNode(f.getName());
                if (f.getName().lastIndexOf(".") != -1)
                    node.setAllowsChildren(false);
                remote.add(node);
            }
            if (remote.toString().contains("remote")){
                try {
                    String name = client.GetWorkingDirPath(remote.toString().replace("remote",""));
                    if(!name.equals(remote.toString() + File.separator))
                        remote.add( new DefaultMutableTreeNode("[ " + name + " ]"));
                } catch (ServerConnectionException ex) {
                    JOptionPane.showConfirmDialog(rootPane, ex, "Get working dir path error", JOptionPane.OK_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE);
                } catch (UsernameOrPasswordIncorrectException | ClientNotLoggedInException | CreateAccountException | MakeDirException | RemoveFileOrDirException | CopyFileException | GetFileContentException ex) {} catch (UploadException ex) {
                    Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if(!homePath.equals(File.listRoots()[0].toString()))
                remote.add( new DefaultMutableTreeNode("[ " + homePath + " ]"));
        } else
            System.out.println("Files are null");
        UpdateTree();
    }
    
    private void fillServersList() {
        if (client.getOnlineServers() == null ) return;
        this.onlineServer = new ArrayList<>(client.getOnlineServers());
        
        DefaultListModel<String> listServersModel = new DefaultListModel<String>();
        for(DataAddress da : onlineServer) {
            listServersModel.addElement(da.getName());
        }
        jListServers.setModel(listServersModel);
    }
    
    private void fillClientsList() {
        if (client.getOnlineClients() == null ) return;
        this.onlineClient = new ArrayList<>(client.getOnlineClients());
        
        DefaultListModel<String> listClientsModel = new DefaultListModel<String>();
        for(DataAddress da : onlineClient) {
            listClientsModel.addElement(da.getName());
        }
        jListClients.setModel(listClientsModel);
    }
    
    private void fillMessageTextArea() {
        if(this.client.getMessage() != null)
            this.jTextAreaMessages.setText(this.jTextAreaMessages.getText() + "\n" + client.getMessage());
    }

    @Override
    public void update(Observable o, Object arg) {
        fillClientsList();
        fillServersList();
        fillMessageTextArea();
        repaint();
    }
}
